
-- DEFENSE ASSET MANAGEMENT SYSTEM
-- 02_sequences.sql — Sequences for Auto-Incrementing PKs


-- Drop existing sequences for re-runs
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE manufacturer_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE weapon_model_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE unit_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE custodian_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE weapon_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE custody_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE maintenance_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ammo_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE compatibility_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE audit_log_seq'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- Create sequences starting after manually inserted data
CREATE SEQUENCE manufacturer_seq   START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE weapon_model_seq   START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE unit_seq           START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE custodian_seq      START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE weapon_seq         START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE custody_seq        START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE maintenance_seq    START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE ammo_seq           START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE compatibility_seq  START WITH 101 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE audit_log_seq      START WITH 101 INCREMENT BY 1 NOCACHE;

PROMPT '>>> All 10 sequences created successfully.';
